/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rrvWeyzp0vt
 */
import { CardContent, Card } from "@/app/ui/components/dishes/card"

export function DishList() {
  return (
    <div className="bg-white">
      <div className="p-8">
        <h2 className="text-2xl font-semibold mb-6">Discover Something New</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          <Card className="w-full">
            <img
              alt="Steak Frites"
              className="w-full h-auto"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <CardContent>
              <h3 className="text-lg font-semibold">Steak Frites</h3>
              <p className="text-sm text-gray-600">French</p>
            </CardContent>
          </Card>
          <Card className="w-full">
            <img
              alt="Soup Dumpling"
              className="w-full h-auto"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <CardContent>
              <h3 className="text-lg font-semibold">Soup Dumpling</h3>
              <p className="text-sm text-gray-600">Chinese</p>
            </CardContent>
          </Card>
          <Card className="w-full">
            <img
              alt="Jjajangmyeon"
              className="w-full h-auto"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <CardContent>
              <h3 className="text-lg font-semibold">Jjajangmyeon</h3>
              <p className="text-sm text-gray-600">Korean</p>
            </CardContent>
          </Card>
          <Card className="w-full">
            <img
              alt="Ceviche"
              className="w-full h-auto"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <CardContent>
              <h3 className="text-lg font-semibold">Ceviche</h3>
              <p className="text-sm text-gray-600">Peruvian</p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
