/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/s8wZcCX1gME
 */
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/app/ui/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/app/ui/ui/sheet"

export function Component() {
  return (
    <nav className="bg-[#FFA500] p-4 flex items-center justify-between">
      <div className="flex items-center space-x-4">
        <PocketKnifeIcon className="text-white h-6 w-6" />
      </div>
      <div className="flex-grow mx-4">
        <div className="relative">
          <MicroscopeIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
          <Input
            className="pl-10 pr-4 py-2 w-full rounded-full"
            placeholder="Search for dishes, cuisines..."
            type="search"
          />
        </div>
      </div>
      <div className="flex space-x-4 hidden md:flex">
        <Link className="text-white font-semibold" href="#">
          Dishes
        </Link>
        <Link className="text-white font-semibold" href="#">
          Food Fairs
        </Link>
        <Link className="text-white font-semibold" href="#">
          About
        </Link>
      </div>
      <div className="md:hidden">
        <Sheet>
          <SheetTrigger asChild>
            <Button size="icon" variant="outline">
              <MenuIcon className="text-white h-6 w-6" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right">
            <div className="flex flex-col items-end space-y-4 py-4">
              <Link className="text-white font-semibold" href="#">
                Dishes
              </Link>
              <Link className="text-white font-semibold" href="#">
                Food Fairs
              </Link>
              <Link className="text-white font-semibold" href="#">
                About
              </Link>
            </div>
          </SheetContent>
        </Sheet>
      </div>
    </nav>
  )
}


function PocketKnifeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 2v1c0 1 2 1 2 2S3 6 3 7s2 1 2 2-2 1-2 2 2 1 2 2" />
      <path d="M18 6h.01" />
      <path d="M6 18h.01" />
      <path d="M20.83 8.83a4 4 0 0 0-5.66-5.66l-12 12a4 4 0 1 0 5.66 5.66Z" />
      <path d="M18 11.66V22a4 4 0 0 0 4-4V6" />
    </svg>
  )
}


function MicroscopeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 18h8" />
      <path d="M3 22h18" />
      <path d="M14 22a7 7 0 1 0 0-14h-1" />
      <path d="M9 14h2" />
      <path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2Z" />
      <path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
